version: '3'

services:
  proxy-service:
    build: 
      context: ./proxy-service/
      dockerfile: ./multi_stage/Dockerfile
    ports:
      - 9090:9090
    depends_on:
      - fibonnaci-server
  fibonnaci-server:
    build:
      context: ./fibonacci-server/
      dockerfile: ./multi_stage/Dockerfile
    ports:
      - 9091:9091